/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface Note {
    title: string;
    created: bigint;
    content: string;
    tags: Array<string>;
    pinned: boolean;
    updated: bigint;
}
export interface backendInterface {
    createNote(arg0: string, arg1: string, arg2: Array<string>, arg3: boolean): Promise<bigint>;
    deleteNote(arg0: bigint): Promise<boolean>;
    getNote(arg0: bigint): Promise<Note | null>;
    listNotes(): Promise<Array<[bigint, Note]>>;
    updateNote(arg0: bigint, arg1: string, arg2: string, arg3: Array<string>, arg4: boolean): Promise<boolean>;
}
import type { Note as _Note } from "./declarations/backend.did";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async createNote(arg0: string, arg1: string, arg2: Array<string>, arg3: boolean): Promise<bigint> {
        const result = await this.actor.createNote(arg0, arg1, arg2, arg3);
        return result;
    }
    async deleteNote(arg0: bigint): Promise<boolean> {
        const result = await this.actor.deleteNote(arg0);
        return result;
    }
    async getNote(arg0: bigint): Promise<Note | null> {
        const result = await this.actor.getNote(arg0);
        return from_candid_opt_n1(result);
    }
    async listNotes(): Promise<Array<[bigint, Note]>> {
        const result = await this.actor.listNotes();
        return result;
    }
    async updateNote(arg0: bigint, arg1: string, arg2: string, arg3: Array<string>, arg4: boolean): Promise<boolean> {
        const result = await this.actor.updateNote(arg0, arg1, arg2, arg3, arg4);
        return result;
    }
}
function from_candid_opt_n1(value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
