/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Note {
  'title' : string,
  'created' : bigint,
  'content' : string,
}
export interface _SERVICE {
  'createNote' : ActorMethod<[string, string], bigint>,
  'deleteNote' : ActorMethod<[bigint], boolean>,
  'getNote' : ActorMethod<[bigint], [] | [Note]>,
  'listNotes' : ActorMethod<[], Array<[bigint, Note]>>,
  'updateNote' : ActorMethod<[bigint, string, string], boolean>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];