/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Note = IDL.Record({
    'title' : IDL.Text,
    'created' : IDL.Int,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'pinned' : IDL.Bool,
    'updated' : IDL.Int,
  });
  
  return IDL.Service({
    'createNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'deleteNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
    'listNotes' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Note))], ['query']),
    'updateNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };